services:
  core:
    build:
      context: ..
      dockerfile: core/Dockerfile
      args:
        HTTP_PROXY: ${HTTP_PROXY}
        http_proxy: ${http_proxy}
        HTTPS_PROXY: ${HTTPS_PROXY}
        https_proxy: ${https_proxy}
    env_file:
      - ../../config/core-config-envs
    logging:
      driver: "json-file"
    restart: on-failure
    depends_on:
      glowroot-central:
        condition: service_started
      rabbitmq:
        condition: service_healthy
  rabbitmq:
    build:
      context: .
      dockerfile: ./init/rabbitmq/Dockerfile.rabbitmq
    env_file:
      - ../../config/rabbitmq-config-envs
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_ADMIN_PORT}:15672"
#    volumes:
#      - type: bind
#        source: ./init/rabbitmq/definitions/
#        target: /etc/rabbitmq/definitions/
#        read_only: true
#      - type: bind
#        source: ./init/rabbitmq/config/
#        target: /etc/rabbitmq/conf.d/
#        read_only: true
    restart: on-failure
    healthcheck:
      # rabbitmq server crashes if any rabbitmq-diagnostics cmd is run very soon
      # after starting, so can't check too aggressively here
      test: rabbitmq-diagnostics -q check_running
      interval: 30s
      timeout: 10s
      retries: 3

  rabbitmq-init:
      build:
        context: .
        dockerfile: ./init/rabbitmq/Dockerfile.rabbitmq
      env_file:
        - ../../config/rabbitmq-config-envs
      depends_on:
        rabbitmq:
          condition: service_healthy
      restart: "no"
      entrypoint: /bin/bash
      command: /definitions-init.sh
  cassandra:
    image: cassandra
    restart: on-failure
    env_file:
      - ../../config/cassandra-config-envs
  glowroot-central:
    build:
      context: ..
      dockerfile: core/Dockerfile.glowroot-central
      args:
        HTTP_PROXY: ${HTTP_PROXY}
        http_proxy: ${http_proxy}
        HTTPS_PROXY: ${HTTPS_PROXY}
        https_proxy: ${https_proxy}
    env_file:
      - ../../config/glowroot-config-envs
    ports:
      - "${GLOWROOT_ADMIN_PORT}:4000"
    restart: on-failure
    depends_on:
       - cassandra
  emap-portal:
    build:
      context: ..
      dockerfile: core/Dockerfile.emap-portal
      args:
        HTTP_PROXY: ${HTTP_PROXY}
        http_proxy: ${http_proxy}
        HTTPS_PROXY: ${HTTPS_PROXY}
        https_proxy: ${https_proxy}
      secrets:
        - portal-build-secrets
    env_file:
      - ../../config/portal-config-envs
    ports:
      - "${PORTAL_PORT}:80"



secrets:
  portal-build-secrets:
    file: ../../config/portal-config-envs

